### ISSUE TITLE
Repo İsminin açıklayıcı Olmaması hakkında

### ISSUE THREAD

**Issue by hmert** [sly01/FinalCalismasi#1]
Sevgili kardeşim Ahmet,

:sparkles:  `FinalCalismasi` :sparkles:  adlı projenin benim gibi konuyu bilmeyen sadece seni Github'tan bilen birisi için çok fazla açıklayıcı olmadığını belirtirim. Projenin README.md dosyasını ve proje ismini açıklayıcı yapmanı, _kişisel tatmin_in ve _takipçilerine verdiğin değer_den dolayı uygun bir vakitte yapacağını düşünüyorum.

Meşhur bir laf vardır.

> If you're going through hell, keep going.
> - Churchill

[Deli gibi sevmek](https://www.youtube.com/watch?v=5P8-E1DWI7I) ruhumuzda var gardaşım. Sev bu işi, `/ağ/bin` gibi [sev beni](https://www.youtube.com/watch?v=gsr-diSugWk)

**Comment by sly01** [comment]
Android final sinavi icin yapilan calismaya katilip tekrar incelemek icin arkadaslarin istegi uzerine acilmis bir repodur. Iste ne yapalim private repo hakki kalmayinca boyle biraz public oldu ama bir daha ki sefere daha dikkatli olalim. :+1:  Tavsiyen icin tesekkur ederim abicim. Diger takipci arkadaslardan ozur dilerim. Fakat kodlari olabildigi kadar sade yazmaya calistik detaylandirmak isteyenleri bekleriz. :) Mesela kameradan alinan fotoyu compress degilde external tarafi yazip atmak gibi bir katki guzel olabilir.
